name: e2e-test
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4
     - name: Cypress run
       uses: cypress-io/github-action@v6
       with:
         start: npm start
         spec: cpyress/e2e/my_first_test.cy.ts
